name: App Test and Lint

on:
  workflow_dispatch:
  workflow_call:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: RobinThrift/action-setup-just@v1

    - uses: actions/setup-node@v4
      with:
        node-version: "latest"

    - name: "Lint App"
      env:
        BIOME_REPORTER: "github"
      run: |
        cd app && \
        just install && \
        just lint

  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: RobinThrift/action-setup-just@v1

    - uses: actions/setup-node@v4
      with:
        node-version: "latest"

    - uses: actions/cache@v4
      with:
        path: app/src/external/sqlite-wasm/build
        key: sqlchiper-v4.6.1

    - name: "Test"
      run: |
        cd app
        just install
        ./node_modules/.bin/playwright install chromium-headless-shell
        just test

