name: Release

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build-OCI-Image:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - uses: RobinThrift/action-setup-just@v1

    - uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Inspect builder
      run: |
        echo "Name:      ${{ steps.buildx.outputs.name }}"
        echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
        echo "Status:    ${{ steps.buildx.outputs.status }}"
        echo "Flags:     ${{ steps.buildx.outputs.flags }}"
        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: "$"
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Image
      env:
        VERSION: ${{ github.ref_name }}
        DOCKER_EXTRA_ARGS: "--push --cache-from type=gha,scope=stuff --cache-to type=gha,scope=stuff,mode=max"
      run:
        just build-oci-image

  Create-Release:
    needs: [Build-OCI-Image]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: ncipollo/release-action@v1
      with:
        bodyFile: "CHANGELOG/CHANGELOG-${{ github.ref_name }}.md"
        allowUpdates: true

