name: Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  Lint-Server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: "stable"
    - uses: RobinThrift/action-setup-just@v1

    - name: "Lint Go"
      env:
        GO_LINT_REPORTER: "github-actions"
      run: |
        cd server && \
        just lint

  Lint-App:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: RobinThrift/action-setup-just@v1
    - name: "Lint App"
      env:
        BIOME_REPORTER: "github"
      run: |
        cd app && \
        just install && \
        just lint


  Test-Server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: "stable"
    - uses: RobinThrift/action-setup-just@v1

    - name: "Test"
      env:
        GO_TEST_REPORTER: "github-actions"
        EXPORT_REPORT: "true"
      run: |
        cd server &&
        just test

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: "Test Results"
        files: |
          server/*.junit.xml

  Test-App:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: RobinThrift/action-setup-just@v1
    - uses: actions/cache@v4
      with:
        path: app/src/external/sqlite-wasm/build
        key: sqlchiper-v4.6.1

    - name: "Test"
      run: |
        cd app && \
        just install && \
        npx playwright install && \
        just test
